"""All sizing constants, colors, MIDI ranges, and layout helpers.

Everything in the app derives from a single white key's width.
Change INITIAL_KEY_WIDTH and everything else scales proportionally.
"""

from PyQt6.QtGui import QColor

# --- Colors ---
DEFAULT_HIGHLIGHT_COLOR = QColor(80, 148, 212)  # Arch Blue (#5094d4)
BACKGROUND_COLOR = QColor(120, 120, 120)         # Grey canvas behind the keys

# --- MIDI note range ---
# A standard piano spans A0 (MIDI 21) to C8 (MIDI 108).
MIDI_NOTE_MIN = 21   # A0
MIDI_NOTE_MAX = 108  # C8

# --- Default visible range (3 octaves around Middle C) ---
DEFAULT_START_NOTE = 48  # C3
DEFAULT_END_NOTE = 83    # B5

# --- Key sizing ---
INITIAL_KEY_WIDTH = 32  # pixels — the anchor for all dimensions

# Height ratio limits: white_key_height = white_key_width * height_ratio
MIN_HEIGHT_RATIO = 3    # squat
MAX_HEIGHT_RATIO = 6    # tall

INITIAL_KEY_HEIGHT = INITIAL_KEY_WIDTH * MAX_HEIGHT_RATIO  # pixels

PRACTICAL_MIN_KEY_WIDTH = 15  # pixels

# --- Visual styling ---
KEY_GAP_RATIO = 0.03
KEY_GAP_MIN = 1
KEY_GAP_MAX = 5

SHADOW_DISABLE_WIDTH = 25  # disable shadows below this key width

BLACK_KEY_HEIGHT_RATIO = 0.6
BLACK_KEY_WIDTH_RATIO = 0.8

KEY_CORNER_RADIUS_RATIO = 0.08
KEY_CORNER_RADIUS_MIN = 4

KEYBOARD_CANVAS_MARGIN = 4
KEYBOARD_CANVAS_RADIUS = 6

# --- UI scale ---
# Set in main() from saved settings before the window is created.
# Mutable: other modules should access via `constants.UI_SCALE_FACTOR`,
# not `from constants import UI_SCALE_FACTOR`.
UI_SCALE_FACTOR = 1.0


def scaled(px):
    """Multiply a pixel value by the current UI scale factor."""
    return round(px * UI_SCALE_FACTOR)


# --- Button sizing (base values before scaling) ---
BUTTON_SIZE = 36
BUTTON_AREA_WIDTH = 50
BUTTON_SPACING = 5

# --- Layout margins (base values before scaling) ---
LAYOUT_MARGIN = 5


def total_horizontal_margin():
    """Total horizontal space taken by margins and button columns."""
    return scaled(LAYOUT_MARGIN) * 2 + scaled(BUTTON_AREA_WIDTH) * 2


def min_button_area_height():
    """Minimum height needed to fit 4 buttons stacked vertically."""
    return scaled(BUTTON_SIZE) * 4 + scaled(BUTTON_SPACING) * 3


def min_window_height():
    """Minimum window height so that buttons are never clipped."""
    return min_button_area_height() + scaled(LAYOUT_MARGIN) * 2


# --- MIDI timing ---
MIDI_POLL_INTERVAL = 10
MIDI_SCAN_INTERVAL = 3000
STATUS_MESSAGE_DURATION = 3000

# --- Note names for text rendering on keys ---
NOTE_NAMES_WHITE = ['C', 'D', 'E', 'F', 'G', 'A', 'B']
NOTE_NAMES_BLACK_SHARPS = ['C♯', 'D♯', 'F♯', 'G♯', 'A♯']
NOTE_NAMES_BLACK_FLATS = ['D♭', 'E♭', 'G♭', 'A♭', 'B♭']

# --- Text sizing ratios (all relative to key dimensions) ---
WHITE_TEXT_GAP_RATIO = 0.02
BLACK_TEXT_GAP_RATIO = 0.05
WHITE_KEY_TEXT_WIDTH_RATIO = 0.7
BLACK_KEY_TEXT_WIDTH_RATIO = 0.5
WHITE_KEY_TEXT_AREA_RATIO = 0.4
MIN_FONT_SIZE = 6

# Font family name — set in main() after loading JetBrains Mono.
# Mutable: other modules should access via `constants.LOADED_FONT_FAMILY`.
LOADED_FONT_FAMILY = None

# --- Loudness compensation ---
# Per-note synth gain, indexed by (midi_note - MIDI_NOTE_MIN), A0..C8.
# Generated by tools/generate_loudness_table.py from a psychoacoustic model
# (A-weighting + small-speaker rolloff) so every note sounds equally loud on
# cheap classroom speakers, with a cap so the bass never booms on good ones.
# Regenerate after changing synth._HARMONIC_PROFILES — do not hand-edit.
LOUDNESS_BY_NOTE = [
    4.856, 4.460, 4.120, 3.831, 3.592, 3.386, 3.203, 3.107,
    3.071, 3.079, 3.056, 3.004, 2.925, 2.867, 2.840, 2.851,
    2.844, 2.798, 2.707, 2.636, 2.598, 2.600, 2.586, 2.549,
    2.489, 2.423, 2.377, 2.339, 2.301, 2.249, 2.200, 2.146,
    2.086, 2.020, 1.951, 1.878, 1.798, 1.710, 1.627, 1.555,
    1.496, 1.440, 1.386, 1.334, 1.284, 1.236, 1.190, 1.146,
    1.105, 1.065, 1.027, 0.994, 0.964, 0.937, 0.912, 0.889,
    0.866, 0.845, 0.825, 0.807, 0.790, 0.774, 0.759, 0.744,
    0.729, 0.715, 0.701, 0.688, 0.676, 0.665, 0.654, 0.633,
    0.600, 0.560, 0.522, 0.489, 0.459, 0.432, 0.407, 0.384,
    0.363, 0.343, 0.325, 0.308, 0.292, 0.277, 0.263, 0.251,
]
